#https://davidegerosa.com/githubforlatex/
#https://github.com/marketplace/actions/github-action-for-latex
#Denna är en kombination av de två

name: Build LaTeX document
on:
  push:
    branches:    
      - 'main'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      FILE: main
      RENAME_TO: interpellationsmall
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ env.FILE }}.tex
      - name: move
        run: mkdir -p github_artifacts && mv ${{ env.FILE }}.pdf ./github_artifacts/${{ env.RENAME_TO }}.pdf
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: ./github_artifacts
  deploy:
    # Edit here if compiling multiple papers
    needs: [build_latex]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
  copy-file:
    needs: [build_latex]
    runs-on: ubuntu-latest    
    env:
      FILE: interpellationsmall
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: github_artifacts
          
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: github_artifacts/PDF/${{env.FILE}}.pdf
          destination_repo: 'Z-Teknologsektionen/ztek-dokument'
          destination_folder: 'dokument'
          user_email: 'info.ztyret@ztek.se'
          user_name: 'Ztyret'